name: docs

on:
  push:
    branches:
      - "main"
  workflow_dispatch: # This line makes the workflow manually triggerable

jobs:
  deploy-docs:
    if: (github.event_name == 'release') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install dependencies
        run: poetry install --with docs

      - name: Download data
        run: |
          mkdir -p /opt/conda
          wget https://repo.anaconda.com/miniconda/Miniconda3-py39_24.5.0-0-Linux-x86_64.sh -O /opt/conda/miniconda.sh
          bash /opt/conda/miniconda.sh -b -p /opt/miniconda
          poetry run fedpydeseq2-download-data --only_luad --raw_data_output_path /home/runner/work/fedpydeseq2/docs/examples/data/raw --conda_activate_path /opt/miniconda/bin/activate
          ls /home/runner/work/fedpydeseq2/docs/examples/data/raw
          ls /home/runner/work/fedpydeseq2/docs/examples/data/raw/tcga
          
      - name: Build docs
        run: poetry run mkdocs gh-deploy --force
